Add batch creating prefabs from multiple selected actors in scene tree.
FlaxEngine/FlaxEngine pull request #1027
Opened 2023-04-21 16:46 UTC by Tryibion

Useful for adding many prefab actors at once when dragging from the scene. This does not allow renaming of each prefab on creating.

2023-04-22 15:41 UTC, mafiesto4 requested changes

2023-04-22 15:41 UTC, mafiesto4 commented on Source/Editor/Modules/PrefabsModule.cs
> +        private Actor _actor;
Could you add a comment that it's locally cached actor ref for prefab creation? And maybe rename it to something more self-explanatory.

2023-04-22 15:41 UTC, mafiesto4 commented on Source/Editor/Content/GUI/ContentView.DragDrop.cs
>              // Use only the first actor
This comment can be removed as it's obsolete after this change

2023-04-22 15:41 UTC, mafiesto4 commented on Source/Editor/Modules/PrefabsModule.cs
> +        private void GetActorsTree(List<Actor> list, Actor a)
Could you move this function to `FlaxEditor.Utilities.Utils` as static. Then use it here, in `ActorStaticFlagsEditor` and `ActorLayerEditor` so we reuse more code.

2023-07-21 04:03 UTC, Tryibion commented
Updated to #1261

2023-07-21 04:03 UTC, closed without merging