don't rotate a rigidbody around locked axis by root motion
FlaxEngine/FlaxEngine pull request #2158
Opened 2024-01-05 04:09 UTC by nothingTVatYT

This fix will prevent rotating a rigidbody around locked axis by the root motion delta.

2024-01-10 10:07 UTC, mafiesto4 requested changes

2024-01-10 10:07 UTC, mafiesto4 commented on Source/Engine/Physics/Actors/RigidBody.cpp
> +    if (static_cast<unsigned int>(GetConstraints()) & static_cast<unsigned int>(RigidbodyConstraints::LockRotation))
Use `EnumHasAllFlags(GetConstraints(). RigidbodyConstraints::LockRotation)` for readability (the same for translation).

2024-01-10 10:07 UTC, mafiesto4 commented on Source/Engine/Physics/Actors/RigidBody.cpp
> +        if (constraints & static_cast<unsigned int>(RigidbodyConstraints::LockRotationX))
Use `EnumHasAnyFlags(GetConstraints(). RigidbodyConstraints::LockRotationX)` for readability (the same for Y/Z axes and translation axes too).

2024-01-10 10:07 UTC, mafiesto4 commented on Source/Engine/Physics/Actors/RigidBody.h
> +    API_FUNCTION() void AddMovement(const Vector3& translation, const Quaternion& rotation) override;
Move it down below `// [Actor]` and remove not needed XML doc comments and `API_FUNCTION()` so it's just pure override (base Actor class has proper docs and exposed scripting info).

2024-01-10 10:07 UTC, mafiesto4 commented on Source/Engine/Level/Actors/AnimatedModel.cpp
> +#include "Engine/Physics/Actors/RigidBody.h"
Remove unused include

2024-01-10 17:46 UTC, nothingTVatYT commented
All requested changes done - assuming I understood you correctly that is.

2024-02-06 15:09 UTC, mafiesto4 approved these changes

2024-02-06 17:15 UTC, merged