Hacy fix for https://github.com/FlaxEngine/FlaxEngine/issues/2311
FlaxEngine/FlaxEngine pull request #2316
Opened 2024-03-10 21:31 UTC by cNori

replaced ASSERT with Platform::CheckFailed for now the https://github.com/FlaxEngine/FlaxEngine/issues/2311 can be moved to 1.9

2024-03-11 18:56 UTC, Menotdan requested changes
Consider changing the message to be something like:
```
"Disabling the enabled state of an object in OnStart() is not supported.\n"
"OnStart() is called just before OnEnabled(), which expects the enabled state to be true.\n"
"See:\n"
"https://docs.flaxengine.com/manual/scripting/events.html?tabs=code-csharp\n"
"If you want to force the object to be disabled when the game is started, consider using OnAwake()."
```

2024-03-11 21:49 UTC, cNori commented
i think now it is stable

2024-03-11 23:50 UTC, Menotdan commented
```
"Modification of the Enabled state failed, state was modified before the object got a chance to call Enable().\n"
"This may cause unexpected behavior in your scripts.\n"
"See:\n"
"https://docs.flaxengine.com/manual/scripting/events.html?tabs=code-csharp\n"
"Note:\n"
"If you were trying to disable the object when the game starts, consider using OnAwake()."
```
Maybe a better message now? I tried to modify it less and keep the language more readable.

2024-03-12 11:58 UTC, cNori commented
> ```
> "Modification of the Enabled state failed, state was modified before the object got a chance to call Enable().\n"
> "This may cause unexpected behavior in your scripts.\n"
> "See:\n"
> "https://docs.flaxengine.com/manual/scripting/events.html?tabs=code-csharp\n"
> "Note:\n"
> "If you were trying to disable the object when the game starts, consider using OnAwake()."
> ```
> 
> Maybe a better message now? I tried to modify it less and keep the language more readable.

look ok

2026-05-09 09:20 UTC, closed without merging