Render2D Triangle Functions
FlaxEngine/FlaxEngine pull request #242
Opened 2021-02-15 18:35 UTC by jb-perrier

Render2D Triangle funcs.

2021-02-15 22:33 UTC, mafiesto4 requested changes

2021-02-15 22:33 UTC, mafiesto4 commented on Source/Engine/Render2D/Render2D.h
> +    API_FUNCTION() static void DrawVertices(GPUTexture* t, Array<Vector2> vertices, Array<Vector2> uvs);
I would name it `DrawTexturedTriangles` and use `const Span<Vector2>& vertices` +` const Span<Vector2>& uvs` to make it more optimized (calling from C# won't allocate memory but just pass span as a pointer to fixed C# buffer).

2021-02-15 22:33 UTC, mafiesto4 commented on Source/Engine/Render2D/Render2D.h
> +    API_FUNCTION() static void DrawVertices(Array<Vector2> vertices, Array<Color> colors, bool useAlpha);
I would name it `FillTriangles` and use `const Span<Vector2>& vertices` +` const Span<Color>& colors` to make it more optimized (calling from C# won't allocate memory but just pass span as a pointer to fixed C# buffer).

2021-02-16 09:15 UTC, jb-perrier commented
I'm on macos right now, so i'm unable to compile it. But it should be good.

2021-02-16 09:52 UTC, jb-perrier commented
Looks like not, in checking it tonight.

2021-02-18 09:05 UTC, merged