Add UIMode switch to prefab window.
FlaxEngine/FlaxEngine pull request #3082
Opened 2024-11-29 22:49 UTC by Tryibion

Adds a UIMode to the prefab window to switch between UI and 3d modes. This also caches the state of the mode for each prefab.

![image](https://github.com/user-attachments/assets/e0b7f8f1-18aa-4718-8dd5-9508bf11d837)

2025-01-27 11:10 UTC, mafiesto4 requested changes

2025-01-27 11:10 UTC, mafiesto4 commented on Source/Editor/Viewport/PrefabWindowViewport.cs
> +            _uiModeButton = new ViewportWidgetButton("UI Mode", SpriteHandle.Invalid, null, true);
I think we should use exiting `View` button and add a checkbox for `UI Mode` (via `ViewWidgetShowMenu`).

2025-01-27 11:10 UTC, mafiesto4 commented on Source/Editor/Windows/Assets/PrefabWindow.cs
> +                _viewport.SetInitialUIMode(false);
Could you try using `_hasUILinked` here? So we can still utilize automatic-UI mode when opening UI widget for the first time.

2025-01-28 00:03 UTC, Tryibion commented on Source/Editor/Viewport/PrefabWindowViewport.cs
> +            _uiModeButton = new ViewportWidgetButton("UI Mode", SpriteHandle.Invalid, null, true);
Done

2025-01-28 00:03 UTC, Tryibion commented on Source/Editor/Windows/Assets/PrefabWindow.cs
> +                _viewport.SetInitialUIMode(false);
Done

2025-02-16 19:38 UTC, mafiesto4 approved these changes

2025-02-16 22:53 UTC, merged