Warn if wrong type while setting material parameter.
FlaxEngine/FlaxEngine pull request #3117
Opened 2024-12-23 22:52 UTC by Tryibion

Closes <https://github.com/FlaxEngine/FlaxEngine/issues/3116>

2024-12-27 08:27 UTC, ZaPx64 commented
Thanks!

2025-01-06 20:42 UTC, mafiesto4 requested changes
You could add `Variant::CanCast(const Variant& v, const VariantType& to)` and use Variant casting so it will work better if someone passes eg. `int` for `float` param.

2025-01-06 21:41 UTC, Tryibion commented
> You could add `Variant::CanCast(const Variant& v, const VariantType& to)`

I added that now.

2025-01-06 22:57 UTC, mafiesto4 approved these changes

2025-01-06 23:16 UTC, merged