Add import path UI and button to open folder in asset import settings.
FlaxEngine/FlaxEngine pull request #3128
Opened 2024-12-31 18:40 UTC by Tryibion

Adds import path (non-editable) and button to open the import folder for each asset type

![image](https://github.com/user-attachments/assets/b7fa9c92-e7f8-40e2-9c67-7cb92e426eef)

2024-12-31 18:42 UTC, xxSeys1 commented
This is super cool, but one issue I can see is people getting confused because they can't edit the import path. I don't have much experience with Flax text rendering, but is there a way to maybe grey out the path slightly to make it more obvious that it can't be edited?

Right now the white text suggests that the text is editable in my opinion.

2024-12-31 18:49 UTC, Tryibion commented
maybe, the disabled text color is the text color * 0.6f to be more grey. I guess we could do something inbetween for read only. maybe textcolor * 0.85f? it would look like this: 
![image](https://github.com/user-attachments/assets/67c3d337-118b-4121-8849-f6bc98512874)

2024-12-31 18:57 UTC, Tryibion commented
I added the color change to a different PR here <https://github.com/FlaxEngine/FlaxEngine/pull/3129>

2025-01-06 20:22 UTC, mafiesto4 requested changes
Please, add a utility method in `FlaxEditor.Utilities.Utils` to reuse in different windows and reduce code duplication.

Also, you could try changing button text to `FlaxEditor.Utilities.Constants.ShowInExplorer` so it uses `Finder` name on Mac.

2025-01-06 21:58 UTC, Tryibion commented
> Please, add a utility method in `FlaxEditor.Utilities.Utils` to reuse in different windows and reduce code duplication.

Done.

2025-01-06 22:54 UTC, mafiesto4 approved these changes

2025-01-06 23:16 UTC, merged