Add Low-Level Networking
FlaxEngine/FlaxEngine pull request #316
Opened 2021-03-07 23:00 UTC by Erdroy

This PR adds low-level networking based upon NetworkManager and INetworkDriver, that allows easy transport-layer replacement (ENet, Valve Sockets etc.).

Default network driver implementation is using ENet.

Draft until ready.

2021-05-16 12:38 UTC, mafiesto4 commented
C# API added (<https://github.com/FlaxEngine/FlaxEngine/commit/5e401b6a788909ec77c53d5f6b6869b834464b39>) so we can move forward with this.

2021-06-21 19:44 UTC, Erdroy commented
Marking as ready for review. We have to test this out, make some fixes (if needed) - SAMPLE NEEDED! 
+ docs pages would be awesome, but this will come after the sample is ready.

Idea for the sample: Simple chat that allows multiple clients join to server via ipv4 and port. Basic UI with chat box, client sends message to the server, server sends it to all other clients.

2021-07-01 11:19 UTC, mafiesto4 requested changes
Looks good! I left some comments for improvements. After merging we will need to fix compilation issues on PS4/UWP/XboxOne (or use those platforms online subsystems as network drivers or implement raw driver that runs purely over low-level platform sockets).

2021-07-01 11:19 UTC, mafiesto4 commented on Source/Engine/Networking/NetworkMessage.cpp
> +void NetworkMessage::WriteBytes(uint8* bytes, const int numBytes)
Maybe move `WriteBytes` into `NetworkMessage.h`?

2021-07-01 11:19 UTC, mafiesto4 commented on Source/Engine/Networking/NetworkMessage.cpp
> +void NetworkMessage::ReadBytes(uint8* bytes, const int numBytes)
Maybe move `ReadBytes` into `NetworkMessage.h`?

2021-07-01 11:19 UTC, mafiesto4 commented on Source/Engine/Networking/NetworkMessage.cpp
> +bool NetworkMessage::IsValid() const
Maybe move `IsValid` into `NetworkMessage.h`?

2021-07-01 11:19 UTC, mafiesto4 commented on Source/Engine/Networking/NetworkPeer.cpp
> +    uint32_t LastHostId = 0;
`uint32`  🍔

2021-07-01 11:19 UTC, mafiesto4 commented on Source/Engine/Networking/NetworkPeer.h
> +    bool EndSendMessage(NetworkChannelType channelType, const NetworkMessage& message, Array<NetworkConnection, HeapAllocation> targets);
Pass `targets` as reference to reduce memory allocations.

2021-07-01 11:19 UTC, mafiesto4 commented on Source/Engine/Networking/INetworkDriver.h
> +    virtual void SendMessage(NetworkChannelType channelType, const NetworkMessage& message, Array<NetworkConnection, HeapAllocation> targets) = 0;
Pass `targets` as reference to reduce memory allocations.

2021-07-01 17:47 UTC, Erdroy commented on Source/ThirdParty/enet/enet.Build.cs
> +        LicenseType = LicenseTypes.Custom;
Done

2021-07-01 17:47 UTC, Erdroy commented on Source/Engine/Networking/Drivers/ENetDriver.cpp
> +            if(IsServer() && _peerMap.ContainsKey(connectionId))
Done

2021-07-01 17:53 UTC, mafiesto4 approved these changes

2021-07-02 09:46 UTC, merged